export const mockUsers = [
  {
    id: "user-1",
    name: "Neha Gupta",
    email: "neha@example.com",
    phone: "+91-9876543210",
    role: "user",
    avatar: "",
    createdAt: "2024-01-15T10:30:00.000Z",
  },
  {
    id: "user-2",
    name: "Rohan Mehta",
    email: "rohan@example.com",
    phone: "+91-8765432109",
    role: "user",
    avatar: "",
    createdAt: "2024-02-20T14:00:00.000Z",
  },
  {
    id: "user-3",
    name: "Priya Sharma",
    email: "priya@example.com",
    phone: "+91-7654321098",
    role: "artist",
    avatar: "",
    createdAt: "2024-01-10T09:00:00.000Z",
  },
];

export const mockArtists = [
  {
    id: "artist-1",
    name: "Priya Sharma",
    rating: 4.8,
    reviewCount: 127,
    image: "",
    bio: "Award-winning mehendi artist with over 10 years of experience specializing in bridal mehendi. Known for intricate patterns and deep natural color using organic henna.",
    location: "Mumbai, Maharashtra",
    services: ["Bridal Mehendi", "Arabic Mehendi", "Engagement Mehendi"],
    priceRange: "₹5,000 - ₹25,000",
    portfolioImages: ["", "", "", ""],
    experience: 10,
    specialties: ["Rajasthani", "Mughlai", "Arabic"],
  },
  {
    id: "artist-2",
    name: "Anjali Verma",
    rating: 4.9,
    reviewCount: 203,
    image: "",
    bio: "Bridal mehendi specialist with a passion for traditional Indian designs. Over 15 years of experience making brides look beautiful on their special day.",
    location: "Delhi, India",
    services: ["Bridal Mehendi", "Traditional Mehendi", "Punjabi Mehendi"],
    priceRange: "₹8,000 - ₹35,000",
    portfolioImages: ["", "", "", "", ""],
    experience: 15,
    specialties: ["Rajasthani", "Traditional", "Punjabi"],
  },
  {
    id: "artist-3",
    name: "Rajesh Patel",
    rating: 4.5,
    reviewCount: 89,
    image: "",
    bio: "Contemporary mehendi artist blending modern flair with traditional art. Specializes in fusion designs that combine Indian and Arabic styles.",
    location: "Ahmedabad, Gujarat",
    services: ["Fusion Mehendi", "Arabic Mehendi", "Minimalist Mehendi"],
    priceRange: "₹3,000 - ₹15,000",
    portfolioImages: ["", "", ""],
    experience: 7,
    specialties: ["Fusion", "Contemporary", "Geometric"],
  },
  {
    id: "artist-4",
    name: "Meera Iyer",
    rating: 4.7,
    reviewCount: 156,
    image: "",
    bio: "Chennai-based mehendi artist known for intricate South Indian designs. Expert in bridal and festive mehendi with natural henna.",
    location: "Chennai, Tamil Nadu",
    services: ["Bridal Mehendi", "South Indian Mehendi", "Feet Mehendi"],
    priceRange: "₹4,000 - ₹20,000",
    portfolioImages: ["", "", "", ""],
    experience: 12,
    specialties: ["South Indian", "Bridal", "Traditional"],
  },
  {
    id: "artist-5",
    name: "Vikram Singh",
    rating: 4.6,
    reviewCount: 112,
    image: "",
    bio: "Arabic mehendi expert based in Jaipur. Known for bold, elegant patterns inspired by Middle Eastern art with a desi twist.",
    location: "Jaipur, Rajasthan",
    services: ["Arabic Mehendi", "Bridal Mehendi", "Leg Mehendi"],
    priceRange: "₹3,500 - ₹18,000",
    portfolioImages: ["", "", ""],
    experience: 8,
    specialties: ["Arabic", "Geometric", "Contemporary"],
  },
  {
    id: "artist-6",
    name: "Divya Kaur",
    rating: 4.4,
    reviewCount: 67,
    image: "",
    bio: "Chandigarh-based freelance mehendi artist. Creates beautiful, affordable designs for all occasions with a focus on customer satisfaction.",
    location: "Chandigarh, Punjab",
    services: ["Minimalist Mehendi", "Kids Mehendi", "Engagement Mehendi"],
    priceRange: "₹2,000 - ₹10,000",
    portfolioImages: ["", ""],
    experience: 5,
    specialties: ["Minimalist", "Contemporary", "Kids"],
  },
];

export const mockBookings = [
  {
    id: "booking-1",
    artistName: "Priya Sharma",
    artistId: "artist-1",
    userId: "user-1",
    date: "2025-06-15",
    time: "10:00 AM",
    status: "confirmed",
    address: "123, Green Park Colony, Andheri West, Mumbai",
    totalAmount: 15000,
    paymentMethod: "Online",
    services: ["Bridal Mehendi (Full Hands)"],
    phone: "+91-9876543210",
    notes: "",
  },
  {
    id: "booking-2",
    artistName: "Anjali Verma",
    artistId: "artist-2",
    userId: "user-2",
    date: "2025-06-20",
    time: "09:00 AM",
    status: "pending",
    address: "456, Model Town, Delhi",
    totalAmount: 25000,
    paymentMethod: "Cash",
    services: ["Bridal Mehendi (Full Hands + Feet)"],
    phone: "+91-8765432109",
    notes: "",
  },
  {
    id: "booking-3",
    artistName: "Rajesh Patel",
    artistId: "artist-3",
    userId: "user-1",
    date: "2025-05-10",
    time: "11:00 AM",
    status: "completed",
    address: "789, SG Highway, Ahmedabad",
    totalAmount: 8000,
    paymentMethod: "Online",
    services: ["Arabic Mehendi"],
    phone: "+91-9876543210",
    notes: "",
  },
  {
    id: "booking-4",
    artistName: "Meera Iyer",
    artistId: "artist-4",
    userId: "user-2",
    date: "2025-07-01",
    time: "08:00 AM",
    status: "cancelled",
    address: "321, Adyar, Chennai",
    totalAmount: 12000,
    paymentMethod: "Online",
    services: ["South Indian Mehendi"],
    phone: "+91-8765432109",
    notes: "Cancelled due to date conflict",
  },
  {
    id: "booking-5",
    artistName: "Vikram Singh",
    artistId: "artist-5",
    userId: "user-1",
    date: "2025-04-25",
    time: "04:00 PM",
    status: "completed",
    address: "555, MI Road, Jaipur",
    totalAmount: 6000,
    paymentMethod: "Cash",
    services: ["Leg Mehendi"],
    phone: "+91-9876543210",
    notes: "",
  },
  {
    id: "booking-6",
    artistName: "Divya Kaur",
    artistId: "artist-6",
    userId: "user-2",
    date: "2025-07-10",
    time: "02:00 PM",
    status: "confirmed",
    address: "999, Sector 17, Chandigarh",
    totalAmount: 4000,
    paymentMethod: "Online",
    services: ["Engagement Mehendi"],
    phone: "+91-8765432109",
    notes: "",
  },
];

export const mockNotifications = [
  {
    id: "notif-1",
    title: "Booking Confirmed",
    message: "Your booking with Priya Sharma has been confirmed for June 15, 2025 at 10:00 AM.",
    type: "booking",
    read: false,
    createdAt: "2025-06-01T10:00:00.000Z",
  },
  {
    id: "notif-2",
    title: "Payment Received",
    message: "Payment of ₹15,000 for booking with Priya Sharma has been received successfully.",
    type: "payment",
    read: false,
    createdAt: "2025-06-01T10:05:00.000Z",
  },
  {
    id: "notif-3",
    title: "Reminder: Upcoming Booking",
    message: "Your mehendi appointment with Anjali Verma is tomorrow at 9:00 AM. Please be ready!",
    type: "reminder",
    read: true,
    createdAt: "2025-06-19T09:00:00.000Z",
  },
  {
    id: "notif-4",
    title: "New Offer Available",
    message: "Get 20% off on all Arabic Mehendi designs this wedding season. Use code ARABIC20!",
    type: "promotion",
    read: false,
    createdAt: "2025-06-05T08:00:00.000Z",
  },
  {
    id: "notif-5",
    title: "Booking Cancelled",
    message: "Your booking with Meera Iyer on July 1, 2025 has been cancelled as requested.",
    type: "booking",
    read: true,
    createdAt: "2025-06-10T15:30:00.000Z",
  },
  {
    id: "notif-6",
    title: "Rate Your Experience",
    message: "How was your experience with Vikram Singh? Please take a moment to leave a review.",
    type: "review",
    read: true,
    createdAt: "2025-04-26T12:00:00.000Z",
  },
  {
    id: "notif-7",
    title: "Wallet Credited",
    message: "₹6,000 has been credited to your wallet from the completed booking with Vikram Singh.",
    type: "payment",
    read: false,
    createdAt: "2025-04-25T18:00:00.000Z",
  },
  {
    id: "notif-8",
    title: "Artist Replied",
    message: "Priya Sharma has accepted your booking request. Check your bookings for details.",
    type: "booking",
    read: false,
    createdAt: "2025-06-01T09:30:00.000Z",
  },
  {
    id: "notif-9",
    title: "Weekend Special Discount",
    message: "Flat 15% off on all mehendi services this weekend. Book now to avail the offer!",
    type: "promotion",
    read: false,
    createdAt: "2025-06-12T06:00:00.000Z",
  },
  {
    id: "notif-10",
    title: "Account Updated",
    message: "Your profile information has been updated successfully.",
    type: "system",
    read: true,
    createdAt: "2025-05-30T14:00:00.000Z",
  },
];

export const mockWallet = {
  balance: 45000,
  totalEarned: 85000,
  totalWithdrawn: 40000,
  transactions: [
    {
      date: "2025-05-20T14:30:00.000Z",
      id: "txn-1",
      type: "credit",
      amount: 15000,
      status: "completed",
      description: "Payment from Neha Gupta - Bridal Mehendi",
    },
    {
      date: "2025-05-10T16:00:00.000Z",
      id: "txn-2",
      type: "credit",
      amount: 8000,
      status: "completed",
      description: "Payment from Neha Gupta - Arabic Mehendi",
    },
    {
      date: "2025-04-25T18:00:00.000Z",
      id: "txn-3",
      type: "credit",
      amount: 6000,
      status: "completed",
      description: "Payment from Rohan Mehta - Leg Mehendi",
    },
    {
      date: "2025-04-01T10:00:00.000Z",
      id: "txn-4",
      type: "debit",
      amount: 20000,
      status: "completed",
      description: "Withdrawal to Bank Account - HDFC Bank",
    },
    {
      date: "2025-06-01T11:00:00.000Z",
      id: "txn-5",
      type: "debit",
      amount: 20000,
      status: "processing",
      description: "Withdrawal to Bank Account - HDFC Bank",
    },
    {
      date: "2025-03-15T09:00:00.000Z",
      id: "txn-6",
      type: "credit",
      amount: 25000,
      status: "completed",
      description: "Payment from Rohan Mehta - Bridal Mehendi",
    },
    {
      date: "2025-06-05T14:00:00.000Z",
      id: "txn-7",
      type: "credit",
      amount: 31000,
      status: "pending",
      description: "Payment from Anjali Sharma - Engagement Mehendi",
    },
  ],
};

export const mockCategories = [
  { id: "cat-1", name: "Bridal Mehendi", icon: "heart", image: "" },
  { id: "cat-2", name: "Arabic Mehendi", icon: "star", image: "" },
  { id: "cat-3", name: "Indo-Arabic Fusion", icon: "sparkles", image: "" },
  { id: "cat-4", name: "Minimalist Mehendi", icon: "circle", image: "" },
  { id: "cat-5", name: "Leg & Feet Mehendi", icon: "foot", image: "" },
  { id: "cat-6", name: "Hand Mehendi", icon: "hand", image: "" },
  { id: "cat-7", name: "Kids Mehendi", icon: "smile", image: "" },
  { id: "cat-8", name: "Engagement Mehendi", icon: "bell", image: "" },
];

export const mockServices = [
  {
    id: "svc-1",
    name: "Bridal Mehendi (Full Hands + Feet)",
    category: "Bridal Mehendi",
    price: 15000,
    duration: "4-5 hours",
    description:
      "Complete bridal package with intricate designs on both hands and feet using premium natural henna.",
    artistId: "artist-1",
  },
  {
    id: "svc-2",
    name: "Bridal Mehendi (Full Hands)",
    category: "Bridal Mehendi",
    price: 10000,
    duration: "3-4 hours",
    description: "Elegant bridal designs covering both hands up to the forearms.",
    artistId: "artist-2",
  },
  {
    id: "svc-3",
    name: "Arabic Mehendi",
    category: "Arabic Mehendi",
    price: 5000,
    duration: "2-3 hours",
    description: "Bold floral patterns with spaced-out designs popular in Arabic style.",
    artistId: "artist-1",
  },
  {
    id: "svc-4",
    name: "Bridal Mehendi Premium",
    category: "Bridal Mehendi",
    price: 25000,
    duration: "5-6 hours",
    description:
      "Premium bridal package with exclusive designs, darker color guarantee, and touch-up session.",
    artistId: "artist-2",
  },
  {
    id: "svc-5",
    name: "Fusion Mehendi Design",
    category: "Indo-Arabic Fusion",
    price: 7000,
    duration: "2-3 hours",
    description:
      "Contemporary fusion designs blending Indian traditional motifs with Arabic patterns.",
    artistId: "artist-3",
  },
  {
    id: "svc-6",
    name: "Minimalist Mehendi",
    category: "Minimalist Mehendi",
    price: 3000,
    duration: "1-2 hours",
    description:
      "Simple, elegant designs perfect for casual occasions and mehendi beginners.",
    artistId: "artist-3",
  },
  {
    id: "svc-7",
    name: "Traditional South Indian Mehendi",
    category: "Bridal Mehendi",
    price: 12000,
    duration: "4-5 hours",
    description:
      "Authentic South Indian mehendi designs with intricate detailing and cultural motifs.",
    artistId: "artist-4",
  },
  {
    id: "svc-8",
    name: "Feet Mehendi Design",
    category: "Leg & Feet Mehendi",
    price: 4000,
    duration: "1-2 hours",
    description:
      "Beautiful mehendi designs specifically for feet, perfect for weddings and festivals.",
    artistId: "artist-4",
  },
  {
    id: "svc-9",
    name: "Arabic Mehendi (Full Hands)",
    category: "Arabic Mehendi",
    price: 8000,
    duration: "3-4 hours",
    description:
      "Comprehensive Arabic mehendi design covering both hands with intricate patterns.",
    artistId: "artist-5",
  },
  {
    id: "svc-10",
    name: "Leg Mehendi",
    category: "Leg & Feet Mehendi",
    price: 3500,
    duration: "1-2 hours",
    description: "Stylish leg mehendi designs from ankles up to calves.",
    artistId: "artist-5",
  },
  {
    id: "svc-11",
    name: "Engagement Mehendi",
    category: "Engagement Mehendi",
    price: 6000,
    duration: "2-3 hours",
    description:
      "Special engagement mehendi designs that are elegant yet not as elaborate as bridal.",
    artistId: "artist-6",
  },
  {
    id: "svc-12",
    name: "Kids Mehendi",
    category: "Kids Mehendi",
    price: 2000,
    duration: "1 hour",
    description:
      "Fun and simple mehendi designs for children, using child-safe natural henna.",
    artistId: "artist-6",
  },
];

export const mockCoupons = [
  {
    id: "coupon-1",
    code: "WELCOME20",
    discountPercent: 20,
    maxDiscount: 1000,
    minOrder: 3000,
    expiryDate: "2025-12-31T23:59:59.000Z",
  },
  {
    id: "coupon-2",
    code: "WEDDING15",
    discountPercent: 15,
    maxDiscount: 2000,
    minOrder: 10000,
    expiryDate: "2025-08-31T23:59:59.000Z",
  },
  {
    id: "coupon-3",
    code: "FESTIVE10",
    discountPercent: 10,
    maxDiscount: 500,
    minOrder: 2000,
    expiryDate: "2025-07-15T23:59:59.000Z",
  },
  {
    id: "coupon-4",
    code: "MEHENDI25",
    discountPercent: 25,
    maxDiscount: 3000,
    minOrder: 15000,
    expiryDate: "2025-09-30T23:59:59.000Z",
  },
];

export const mockReviews = [
  {
    id: "review-1",
    userId: "user-1",
    userName: "Neha Gupta",
    userAvatar: "",
    rating: 5,
    comment:
      "Absolutely stunning work! Priya did an amazing job with my bridal mehendi. The color was so dark and the design was exactly what I wanted.",
    date: "2025-05-20T14:30:00.000Z",
  },
  {
    id: "review-2",
    userId: "user-2",
    userName: "Rohan Mehta",
    userAvatar: "",
    rating: 4,
    comment:
      "Great experience with Anjali. Professional and punctual. The mehendi turned out beautiful and lasted over two weeks.",
    date: "2025-06-22T11:00:00.000Z",
  },
  {
    id: "review-3",
    userId: "user-1",
    userName: "Neha Gupta",
    userAvatar: "",
    rating: 5,
    comment:
      "Rajesh did Arabic mehendi for my sister and it was incredible. Very creative patterns and affordable pricing.",
    date: "2025-05-12T16:00:00.000Z",
  },
  {
    id: "review-4",
    userId: "user-2",
    userName: "Rohan Mehta",
    userAvatar: "",
    rating: 3,
    comment:
      "Meera is very talented but was a bit late for the appointment. The design quality was good though.",
    date: "2025-07-02T10:00:00.000Z",
  },
  {
    id: "review-5",
    userId: "user-1",
    userName: "Neha Gupta",
    userAvatar: "",
    rating: 5,
    comment:
      "Vikram did leg mehendi for my cousin and it was gorgeous. Very clean, precise work with stunning detailing.",
    date: "2025-04-26T18:00:00.000Z",
  },
  {
    id: "review-6",
    userId: "user-2",
    userName: "Rohan Mehta",
    userAvatar: "",
    rating: 4,
    comment:
      "Divya created a lovely engagement mehendi design. Very friendly and accommodating with design changes.",
    date: "2025-07-11T12:00:00.000Z",
  },
];
